### ISSUE TITLE
文件列表有数据，但列表空白，不显示

### ISSUE THREAD

**Issue by ydcool** [zhen-ke/electron-qiniu#3]
系统：win10 1903
Electron: ^6.0.1 (4.x版本打包安装后无法启动，升级到6.x后解决)

像是 el-table 没有渲染数据，刚入门 vue 不知道问题出在哪里

![微信截图_20190810054003](https://user-images.githubusercontent.com/5668295/62810911-31d03b80-bb32-11e9-8ec0-5840b087c6df.jpg)

![无标题](https://user-images.githubusercontent.com/5668295/62811276-ace62180-bb33-11e9-9e90-b450f4a1941a.jpg)

**Comment by ydcool** [comment]
已解决，需要将 element-ui 加入 webpack 白名单。

**Comment by Yan9Gan** [comment]
> 已解决，需要将 element-ui 加入 webpack 白名单。

是在 webpack.renderer.config.js 中添加白名单吗，我添加了但还是没有成功渲染。
